### ISSUE TITLE
self.root_window.unregister_event_manager(self.hover_manager)

### ISSUE THREAD

**Issue by jacksonkirka** [pythonic64/hover#1]
Dear Filip:
I found this error when implementing your Hover solution.  I worked very well.  Thank you so much.  There error has
to do with type list vs I think dict.  Please respond via my email jacksonkirka@gmail.com.

Found error and documenting:

Traceback (most recent call last):
File "C:\Users\jacks\Downloads\kpicture\main.py", line 1561, in <module>
KPictureApp().run()
File "C:\Users\jacks\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\app.py", line 957, in run
self._stop()
File "C:\Users\jacks\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\app.py", line 985, in _stop
self.dispatch('on_stop')
File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
File "C:\Users\jacks\Downloads\kpicture\main.py", line 1556, in on_stop
self.root_window.unregister_event_manager(self.hover_manager)
File "C:\Users\jacks\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\core\window\init.py", line 1172, in unregister_event_manager
self.event_managers.remove(manager)
ValueError: list.remove(x): x not in list
PS C:\Users\jacks\Downloads\kpicture>

**Comment by jacksonkirka** [comment]
This is the fix.   For future users use button event method but make sure hover_manager closed FIRST. 
    def kpicture_stop(self):

        '''
        kpicture_stop gracefully shutsdown KPicture and saves the state of the
        application.
        '''

        self.root_window.unregister_event_manager(self.hover_manager)
        self.save_cache(self.cache_list)
        self.save_dir(self._directories)
        self.save_curdir(self.curdir)
        self.config.write()
        self.save_settings_config_file(self.settingsfile)
        self.save_settings_list(self._settings)
        self.stop()

**Comment by jacksonkirka** [comment]
Issue is fixed and everyone globally can benefit from this example of a fix.
